### ISSUE TITLE
🛑Snipcart SendGrid Account Misused, Causing Email Delays

### ISSUE THREAD

**Issue by sebastienlemi** [snipcart/status#62]
Snipcart's SendGrid account has been used for malicious purposes, resulting in the sending queue being filled with unwanted emails. This issue is causing significant delays in the delivery of legitimate transactional emails, including order confirmations.

As a result, customers are experiencing slow email reception, impacting the user experience and potentially causing confusion about order status.

**Comment by sebastienlemi** [comment]
Incident has been resolved.

**Comment by marki79** [comment]
We are still not receiving any emails from Snipcart via SendGrid on our account. There is no delay; the emails simply don’t arrive at all. I tested this with two separate domains. Previously, everything worked perfectly. Need help on that!

**Comment by IvoJager** [comment]
We are also not receiving any emails, nor are our customers.

**Comment by sebastienlemi** [comment]
https://support.snipcart.com/t/sendgrid-email-deliverability/3487

**Comment by marki79** [comment]
We have authenticated our domain as required, and the emails were sent successfully before. However, they are no longer being received. I have already authenticated the domain with SendGrid, so I'm unsure what else I can do.

**Comment by IvoJager** [comment]
If it provides any clues, we have also been unable to receive Snipcart forum registration emails...

**Comment by sebastienlemi** [comment]
At this time, we are in communication with SendGrid to see what can be done. Meanwhile, those who have reached out to us about similar issues have created a free SendGrid account and moved away from our shared account. A free SendGrid account allows for 100 emails per day.

**Comment by marki79** [comment]
So I made a SendGrid account on my own, and it works for customer emails, but I don't receive any notifications. I toggled both checkboxes on (Notify me and BCC to another address), but I still don't receive any emails for new orders... Any ideas?

**Comment by IvoJager** [comment]
Yay! We just - belatedly - received all outstanding communications from Snipcart. This includes orders and support forum communication.
